flock-web/flock_web/blueprints/main/__init__.py
import json
import collections
from urllib.parse import urlparse, urljoin

from flask import render_template, Blueprint, redirect, url_for, flash, session, abort, request, render_template_string, jsonify, current_app
import flask_login

from flask_wtf import FlaskForm
import wtforms as wtf
from wtforms import validators

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

from flock import model

from flock_web.app import db
from flock_web import model as fw_model
from flock_web.model import User


bp_main = Blueprint(
    'main',
    __name__,
    template_folder='templates',
    )


@bp_main.route('/')
@flask_login.login_required
def welcome():

    #return redirect(url_for('collection.user_eval_topics', collection='RTS17'))

    collections = ((c,) for c in current_app.config['COLLECTIONS'])

    return render_template(
        'main/welcome.html',
        collections=collections,
        current_app=current_app,
    )


class LoginForm(FlaskForm):
    first_name = wtf.StringField('First name', [validators.Required()])
    last_name = wtf.StringField('Last name', [validators.Required()])

    next = wtf.HiddenField('Next', [validators.Optional()])

    def __init__(self, *args, **kwargs):
        FlaskForm.__init__(self, *args, **kwargs)
        self.user = None

    def validate(self):
        rv = FlaskForm.validate(self)
        if not rv:
            return False

        if not is_safe_url(self.next.data):
            return False

        user = db.session.query(User).filter_by(first_name=self.first_name.data, last_name=self.last_name.data).one_or_none()
        if user is None:
            flash('''Such user doesn't exist''', 'danger')
            return False

        self.user = user
        return True


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and ref_url.netloc == test_url.netloc


@bp_main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():
        session['user_id'] = form.user.id
        return redirect(form.next.data or url_for('.welcome'))

    return render_template('main/login.html', form=form)


@bp_main.route('/logout')
@flask_login.login_required
def logout():
    flask_login.logout_user()
    return redirect(url_for('.login'))


class TopicForm(FlaskForm):
    title = wtf.StringField('Title', [validators.Required()])
    description = wtf.TextAreaField('Description')
    narrative = wtf.TextAreaField('Narrative')

    difficulty = wtf.RadioField(
        'How easy was it to develop this topic?',
        [validators.Optional()],
        choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')],
    )
    familiarity = wtf.RadioField(
        'How familiar are you with the topic?',
        [validators.Optional()],
        choices=[
            ('VIN', 'Familiar, I was checking a specific piece of information.'),
            ('CIN', 'Familiar, but I was interested in gaining new knowledge about the topic.'),
            ('MIN', 'Unfamiliar, the search was in more or less unknown knowledge area.'),
        ],
    )
    inspiration = wtf.StringField('What was the inspiration for this topic?')
    notes = wtf.TextAreaField('General comment.')

    topic_id = wtf.HiddenField()


@bp_main.route('/topics', methods=['POST'], endpoint='topic_post')
@bp_main.route('/topics', methods=['GET'], endpoint='topics')
@bp_main.route('/topics/<topic_id>', endpoint='topic')
@flask_login.login_required
def topic(topic_id=None):
    if request.method == 'POST':

        topic_id = request.form.get('topic_id', type=int)
        selection_args = json.loads(request.form['selection_args']) if 'selection_args' in request.form else None

        new_topic_created = False
        new_query_created = False

        if topic_id is None:
            collection = request.form['return_to_collection']
            query = fw_model.TopicQuery(**selection_args)
            redirect_to = url_for('collection.tweets', collection=collection, q=query.query, filter=query.filter, cluster=query.cluster, **query.filter_args_dict)

            return redirect(redirect_to)

        if topic_id > 0:
            topic = db.session.query(fw_model.Topic).get(topic_id)
            assert topic.user == flask_login.current_user

            form = TopicForm()
            if form.validate_on_submit():
                topic.title = form.title.data
                topic.description = form.description.data
                topic.narrative = form.narrative.data

                if topic.questionnaire is None:
                    topic.questionnaire = fw_model.TopicQuestionnaire()

                topic.questionnaire.answer = {
                    'difficulty': form.difficulty.data,
                    'familiarity': form.familiarity.data,
                    'inspiration': form.inspiration.data,
                    'notes': form.notes.data,
                }

        else:
            # New topic is requested
            topic = fw_model.Topic(title=selection_args['query'])
            topic.user = flask_login.current_user

            new_topic_created = True
            db.session.flush()

        redirect_to = url_for('.topic', topic_id=topic.id)

        if 'selection_args' in request.form:
            # TODO: This check is not enought, when a query is entered and then a topic is chosen,
            # a new query is created, independently whether it already exists or not.
            query = fw_model.TopicQuery(**selection_args)
            topic.queries.append(query)

            if 'return_to_collection' in request.form:
                collection = request.form['return_to_collection']
                redirect_to = url_for('collection.tweets', topic=topic.id, collection=collection, q=query.query, filter=query.filter, cluster=query.cluster, **query.filter_args_dict)

            new_query_created = True

        db.session.commit()

        if new_topic_created:
            flash(
                render_template_string(
                    '''
                    A new topic <a class="alert-link" href="{{ topic_url }}">"{{topic.title}}"</a> is created.
                    ''',
                    topic=topic,
                    topic_url=url_for('main.topic', topic_id=topic.id)
                ),
                'success',
            )

        elif new_query_created:
            flash(
                render_template_string(
                    '''
                    A new query was assigned to the topic <a class="alert-link" href="{{ topic_url }}">"{{topic.title}}"</a>.
                    ''',
                    topic=topic,
                    topic_url=url_for('main.topic', topic_id=topic.id)
                ),
                'success',
            )

        return redirect(redirect_to)

    if topic_id is None:
            topics = db.session.query(fw_model.Topic).filter_by(user=flask_login.current_user).order_by(fw_model.Topic.id)
            return render_template(
                'main/topics.html',
                topics=topics,
                current_app=current_app,
            )

    topic = db.session.query(fw_model.Topic).get(topic_id)
    assert topic.user == flask_login.current_user

    tweets = db.session.query(model.Tweet).filter(
        model.Tweet.tweet_id.in_(
            sa.select([fw_model.RelevanceJudgment.tweet_id])
            .where(fw_model.RelevanceJudgment.topic_id==topic.id)
            .where(fw_model.RelevanceJudgment.judgment==1)
        )
    ).distinct(model.Tweet.tweet_id).all()

    form = TopicForm(
        title=topic.title,
        description=topic.description,
        narrative=topic.narrative,
        topic_id=topic.id,
        tweets=tweets,

        difficulty=topic.questionnaire.answer.get('difficulty') if topic.questionnaire is not None else None,
        familiarity=topic.questionnaire.answer.get('familiarity') if topic.questionnaire is not None else None,
        inspiration=topic.questionnaire.answer.get('inspiration')  if topic.questionnaire is not None else None,
        notes=topic.questionnaire.answer.get('notes')  if topic.questionnaire is not None else None,
    )

    return render_template(
        'main/topic.html',
        form=form,
        topic=topic,
        tweets=tweets,
        current_app=current_app,
    )


@bp_main.route('/topics.json')
def topics_json():
    topics = db.session.query(fw_model.Topic).order_by(fw_model.Topic.user_id, fw_model.Topic.id)

    result = [
        collections.OrderedDict(
            [
                ('topid', topic.id),
                ('title', topic.title),
                ('description', topic.description),
                ('narrative', topic.narrative),
                ('relevant_count', topic.judgment_count(1) + topic.judgment_count(2)),
                ('irrelevant_count', topic.judgment_count(0) + topic.judgment_count(-1)),
                ('queries', len(topic.queries)),
                ('user', {'first_name': topic.user.first_name, 'last_name': topic.user.last_name}),
            ]
        )
        for topic in topics
    ]

    return jsonify(result)


@bp_main.route('/relevance', methods=['POST'])
@flask_login.login_required
def relevance():
    # XXX: this clearly needs validation.
    data = request.get_json()

    tweet_id = int(data.get('tweet_id'))
    judgment = data.get('judgment')

    topic_id = data.get('topic_id')
    if topic_id is not None:
        selection_args = data.get('selection_args')
        if selection_args:
            query = db.session.query(fw_model.TopicQuery).filter_by(topic_id=topic_id, **selection_args).first()
            if query is None:
                query = fw_model.TopicQuery(topic_id=topic_id, **selection_args)
                db.session.add(query)
                db.session.flush()

flock-web/flock_web/templates/base.html
{% macro render_pagination(page) %}

  {% set pager = page.link_map(symbol_previous='&laquo;', symbol_next='&raquo;', format='~4~') %}

  <nav aria-label="Page navigation">
    <ul class="pagination">
      {%- for page in [pager.previous_page, pager.first_page] + pager.range_pages + [pager.last_page, pager.next_page] %}
        {% if page.type == 'current_page' %}
          <li class="page-item active">
            <span class="page-link">{{ page.value }}
              <span class="sr-only">(Current page)</span>
            </span>
          </li>
        {% elif page.type == 'span' %}
          <li class="page-item disabled">
            <span class="page-link" aria-label="Ellipsis">
              <span aria-hidden="true">...</span>
              <span class="sr-only">Ellipsis</span>
            </span>
          </li>
        {%- elif page.number != pager.current_page.value %}
          {% if not (page.type == 'first_page' and pager.range_pages[0].type != 'span')
             and not (page.type == 'last_page' and pager.range_pages[-1].type != 'span')
          %}
          <li class="page-item">
            <a class="page-link" href="{{ page.href }}" aria-label="Next">
              <span aria-hidden="true">{{ page.value|safe if page.type not in ('first_page', 'last_page') else page.number }}</span>
            </a>
          </li>
          {% endif %}
        {%- elif page.type not in ('first_page', 'last_page') %}
          <li class="page-item disabled">
            <span class="page-link">
              {{ page.value|safe }}
            </span>
          </li>
        {% endif %}
      {%- endfor %}
    </ul>
  </nav>
{% endmacro %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>{% block title %}flock{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"></link>
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='pace.css') }}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-toggleable-md navbar-fixed-top navbar-dark bg-inverse navbar-inverse bg-inverse fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{{url_for('main.welcome')}}">flock</a>

      <ul class="navbar-nav mr-auto">
        {% block navbar_body  %} {% endblock navbar_body %}
      </ul>

      {% block navbar_extra  %} {% endblock navbar_extra %}

      {% if current_user.is_authenticated %}
        <ul class="navbar-nav float-right">
          <li class="nav-item mr-5">
            <a class="nav-link btn btn-info" href="{{ url_for('main.topics')  }}">Topics</a>
          </li>
          <li class="nav-item mr-3">
            <a class="nav-link" href="{{ url_for('main.user') }}">
            <i class="fa fa-user" aria-hidden="true"></i>
            {{ current_user.first_name }} {{ current_user.last_name }}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link btn btn-outline-danger" href="{{ url_for('main.logout')  }}">Logout</a>
          </li>
        </ul>
      {% endif %}

    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <div class="container">
          <div class="row justify-content-md-center">
            <div class="col-7">
              {% for category, message in messages %}
                <div class="alert alert-{{ {'message': 'danger'}.get(category, category) }} alert-dismissible fade show" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  {{ message|safe }}
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      {% endif %}
    {% endwith %}

    <div class="container-fluid" id='main-content'>
      {% block content %}{% endblock %}
    </div>

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='pace.min.js') }}"></script>

    {% block extra_scripts %}{% endblock %}

    <script type="text/javascript">
      var csrf_token = "{{ csrf_token() }}";

     $.ajaxSetup({
         beforeSend: function(xhr, settings) {
             if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                 xhr.setRequestHeader("X-CSRFToken", csrf_token);
             }
         }
     });
    </script>

  </body>
</html>