flock-web/flock_web/blueprints/collection/__init__.py
from flask import render_template, Blueprint, request, url_for, g, redirect, jsonify, get_template_attribute, Response, stream_with_context, flash, json
import flask_login

import sqlalchemy as sa
from sqlalchemy.orm.exc import NoResultFound
from sqlalchemy.dialects import postgresql

from flock import model
from flock_web.app import db
import flock_web.queries as q
import flock_web.model as fw_model

from sklearn.feature_extraction.text import TfidfVectorizer

bp_collection = Blueprint(
    'collection', __name__,
    static_folder='static',
    template_folder='templates',
    url_prefix='/c/<collection>'
    )


@bp_collection.url_defaults
def add_collection(endpoint, values):
    values.setdefault('collection', getattr(g, 'collection', None))


@bp_collection.url_value_preprocessor
def pull_collection(endpoint, values):
    g.collection = values.pop('collection')

    g.filter_args = sorted(
        (k, sorted(vs))
        for k, vs in request.args.lists()
        if not k.startswith('_') and k not in ('q', 'topic')
    )

    g.selection_args = {
        'collection': g.collection,
        'filter_args': g.filter_args,
        'query': request.args.get('q'),
        **json.loads(request.args.get('selection_args', '{}'))
    }

    g.query = g.selection_args.get('query')
    g.query_type = 'multiword' if g.query is not None and ' ' in g.query else 'singleword'

    topic_id = request.args.get('topic', None, type=int)
    if topic_id is not None:
        g.topic = db.session.query(fw_model.Topic).get(topic_id)
    else:
        g.topic = None


@bp_collection.route('/')
@flask_login.login_required
def index():

    return render_template(
        'collection/index.html',
        collection=g.collection,
    )


@bp_collection.route('/tweets')
@flask_login.login_required
def tweets():

    if not g.query:
        flash('Please enter a query.')

        return (redirect(url_for('.index')))

    # page_num = request.args.get('_page', 1, type=int)
    # items_per_page = request.args.get('_items_per_page', 100, type=int)

    tweet_task, tweet_count = (
        g.celery.send_task(
            'flock_web.tasks.tweets',
            kwargs={
                'collection': g.collection,
                'query': g.query,
                'filter_args': g.filter_args,
                'count': count,
            },
            queue=f'tweets_{g.query_type}',
        ) for count in (False, True)
    )

    selection_for_topic_args = {**g.selection_args}
    del selection_for_topic_args['collection']

    stat_tasks = [
        (
            f_name,
            g.celery.send_task(
                'flock_web.tasks.stats_for_feature',
                kwargs={
                    'feature_name': f_name,
                    'feature_alias': f_alias,
                    'active_features': request.args.getlist(f_name),
                    'filter_args': g.filter_args,
                    'query': g.query,
                    'collection': g.collection,
                },
                queue=f'stats_for_feature_{g.query_type}',
            ),
        )
        for f_name, f_alias in [('screen_names', 'Users'), ('hashtags', 'Hashtags'), ('user_mentions', 'User mentions')]
    ]

    response = Response(
        render_template(
            'collection/tweets.html',
            tweet_task=tweet_task,
            tweet_count=tweet_count,
            stats=stat_tasks,
            query_form_hidden_fields=((k, v) for k, v in request.args.items(multi=True) if not k.startswith('_') and k != 'q'),
            filter_form_hidden_fields=((k, v) for k, v in request.args.items(multi=True) if not k.startswith('_')),
            selection_args=json.dumps(g.selection_args),
            selection_for_topic_args=json.dumps(selection_for_topic_args),
            topics=flask_login.current_user.topics,
            # relevance_judgments={j.tweet_id: j.judgment for j in g.topic.judgments} if g.topic is not None else {},
        ),
    )
    response.headers['X-Accel-Buffering'] = 'no'
    return response


@bp_collection.route('/tweets.jsonl')
def tweets_json():
    tweets = q.build_tweet_query(
        collection=g.collection,
        query=g.query,
        filter_args=g.filter_args,
        possibly_limit=False,
        cluster=g.cluster,
    ).all()

    vectorizer = TfidfVectorizer(binary=True)
    vectors = vectorizer.fit_transform(t.text for t in tweets)

    def generate():
        for t, v in zip(tweets, vectors):
            yield json.dumps(
                {
                    'tweet_id': t.tweet_id,
                    'text': t.text,
                    'tokens': t.features['tokenizer'],
                    'language': t.features['languages'][0],
                    'created_at': t.created_at.isoformat(),
                    'vector': v.toarray().flatten().tolist(),
                }
            ) + '\r\n'

    return Response(stream_with_context(generate()), mimetype='text/plain')


@bp_collection.route('/cluster', methods=['POST'])
@flask_login.login_required
def cluster():
    selection_args = json.loads(request.form['selection_args'])

    task = g.celery.send_task(
        'flock_web.tasks.cluster_selection',
        kwargs={'selection_args': selection_args},
        queue=f'cluster_{g.query_type}'
    )

    location = url_for('.task_result', task_id=task.id)
    return jsonify({'Location': location, 'info': task.info}), 202, {'Location': location}


@bp_collection.route('/cluster/status/<task_id>')
@flask_login.login_required
def cluster_status(task_id):
    task = g.celery.AsyncResult(task_id)
    if task.state == 'PENDING':
        response = {
            'state': task.state,
            'info': {
                'current': 0,
                'total': 1,
            },
            'status': 'Pending...'
        }
    elif task.state != 'FAILURE':
        response = {
            'state': task.state,
            'info': task.info,
        }
    else:
        response = {
            'state': task.state,
            'current': 1,
            'total': 1,
            'status': str(task.info),  # this is the exception raised
        }

    cluster_html_snippet = None
    if task.state == 'SUCCESS':
        clusters = q.build_cluster_query(clustered_selection._id)

        cluster_html_snippet = render_template(
            'collection/cluster_snippet.html',
            clusters=clusters,
        )

    response['cluster_html_snippet'] = cluster_html_snippet

    return jsonify(response)


@bp_collection.route('/tasks/<task_id>')
@flask_login.login_required
def task_result(task_id):
    task = g.celery.AsyncResult(task_id)

    result = {'state': task.state}

    if task.successful():

        if task.result.get('task_name') == 'flock_web.tasks.tweets':

            if task.result['count']:
                render_tweet_count = get_template_attribute('collection/macro.html', 'render_tweet_count')
                result['html'] = render_tweet_count(task.result['data'])
            else:
                result['backendState'] = {}

                if g.topic:
                    result['backendState']['topic'] = {
                        'title': '',
                        'description': '',
                        'narrative': '',
                        'rts_id': g.topic.eval_topic.rts_id if g.topic.eval_topic else None,
                        'topic_id': g.topic.id,
                    }

                    judgments = {
                        str(j.tweet_id): {
                            'assessor': 'missing' if hasattr(j, 'missing') and j.missing else j.judgment,
                            **(
                                {
                                    'crowd_relevant': getattr(j, 'crowd_relevant', 0),
                                    'crowd_not_relevant': getattr(j, 'crowd_not_relevant', 0),
                                } if hasattr(j, 'crowd_relevant') else {}
                            )
                        }
                        for j in (g.topic.eval_topic.judgments if g.topic.eval_topic else g.topic.judgments)
                    }
                else:
                    judgments = {}

                result['backendState']['tweets'] = [
                    {
                        'created_at': t['created_at'],
                        'id': str(t['tweet_id']),
                        #'screen_name': t['features']['repr']['user__screen_name'],
                        #'user_name': t['features']['repr']['user__name'],
                        #'text': t['features']['repr']['text'],
                    }
                    for t in task.result['data'] if str(t['tweet_id'])
                ]

                result['backendState']['judgments'] = judgments

        elif task.result.get('task_name') == 'flock_web.tasks.stats_for_feature':
            render_stats = get_template_attribute('collection/macro.html', 'render_stats')

            features = task.result['data']
            selected_feature_names = set(name for name, _ in features)
            active_feature_names = set(task.result['active_features'])

            missing_feature_names = active_feature_names - selected_feature_names
            features = features + [(name, 0) for name in missing_feature_names]

            result['data'] = task.result
            result['html'] = render_stats(
                feature_name=task.result['feature_name'],
                feature_alias=task.result['feature_alias'],
                features=features,
                active_feature_names=active_feature_names,
                collection=g.collection,
                hidden_fields=[(k, v) for k, v in request.args.items(multi=True) if not k.startswith('_')],
            )
        elif task.result.get('task_name') == 'flock_web.tasks.cluster_selection':
            result['data'] = task.result,
            result['html'] = render_template(
                'collection/cluster_snippet.html',
                clusters=task.result['data'],

flock-web/flock_web/blueprints/collection/templates/collection/base.html
{% extends "base.html" %}

{% block navbar_body %}
{% for c in config.COLLECTIONS %}
<li class="nav-item {% if c == g.collection %}active{% endif %}">
    <a class="nav-link" href="{{ restricted_url(request.endpoint, collection=c) if c != collection else url_for(request.endpoint, collection=collection, show_images='on' if g.show_images else '', filter=g.filter, q=g.query) }}">
        {{ config.get('collection:{}'.format(c),{}).get('title', c) }}
    </a>
</li>
{% endfor %}
{% endblock navbar_body %}

flock-web/flock_web/blueprints/collection/templates/collection/cluster_snippet.html
<div class="card sidebar-element">
    <h3 class="card-header">Clusters</h3>
    <div class="list-group list-group-flush">
        {% for terms, tweet_count in clusters %}
        <a href="{{ restricted_url('.tweets', q='{} {}'.format('({})'.format(g.query) if g.query else '', ' '.join(terms))) }}" class="list-group-item list-group-item-action flex-column align-items-start feature-item">
            <p class="mb-0">{{ ' '.join(terms)  }} ({{ tweet_count|humanize('intword') }})</p>
        </a>
        {% endfor %}
    </div>
</div>

flock-web/flock_web/blueprints/collection/templates/collection/eval_topic.html
{% extends "base.html" %}
{% import "main/macro.html" as m %}
{% import "collection/macro.html" as rm %}
{# {% block title %} {{ form.title.data }} {% endblock %} #}

{% block content %}

<div class="row" id="main-content"></div>

{% endblock content %}

{% block extra_scripts %}
 <script src="{{ url_for('static', filename='bundle.js') }}"></script>

 <script>
   window.BACKEND = {{ state|tojson }};
   window.CSRF_TOKEN = '{{ csrf_token() }}';
   window.JUDGE_TWEET_URL = '{{ url_for('main.relevance') }}';
   window.TOPICS_URL = '{{url_for('.user_eval_topics')}}';
   window.STATE_URL = '{{ url_for('.eval_topic_json', rts_id=eval_topic.rts_id) }}'

   window.judge();
 </script>
{% endblock extra_scripts %}

flock-web/flock_web/blueprints/collection/templates/collection/eval_topic_cluster.html
{% extends "base.html" %}

{% block content %}{% endblock content %}

{% block extra_scripts %}
<script src="{{ url_for('static', filename='bundle.js') }}"></script>
<script>
 window.BACKEND = {{ state|tojson }};
 window.CSRF_TOKEN = '{{ csrf_token() }}';
 window.CLUSTER_URL = '{{ url_for('.cluster_eval_topic', rts_id=eval_topic.rts_id) }}';
 window.ASSIGN_TWEET_TO_CLUSTER_URL = '{{ url_for('.assign_tweet_to_eval_cluster', eval_topic_rts_id=eval_topic.rts_id) }}';
 window.TOPICS_URL = '{{ url_for('.user_eval_topics') }}';
 window.SWAP_CLUSTERS_URL = '{{ url_for('.swap_clusters', eval_topic_rts_id=eval_topic.rts_id) }}';
 window.STATE_URL = '{{ url_for('.cluster_eval_topic_json', rts_id=eval_topic.rts_id) }}'
 window.JUDGE_TWEET_URL = '{{ url_for('main.relevance') }}';

 window.cluster();
</script>
{% endblock extra_scripts %}

flock-web/flock_web/blueprints/collection/templates/collection/eval_topics.html
{% extends "base.html" %}
{% import "collection/macro.html" as m %}

{% block title %} Evaluation Topics {% endblock %}

{% block content %}

  <h1>Evaluation topics ({{ topic_info|count}})</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Total</th>
        <th>Judged</th>
        <th>Relevant</th>
        <th>Clustered</th>
        <th>Queries</th>
      </tr>
    </thead>
    <tbody>
      {%- for rts_id, title, total_count, judged_count, relevant_count, clustered_count, topic_id in topic_info %}
        <tr>
          <td>{{ rts_id }}</td>
          <td>{{ title }}</td>
          <td>{{ total_count }}</td>
          <td>
            <a
              href="{{ url_for('.eval_topic', rts_id=rts_id) }}"
              class="btn {{ "btn-secondary" if total_count == judged_count else "btn-danger"}}"
              >
              {{ judged_count }}
            </a>
          </td>
          <td>{{ relevant_count }}</td>
          <td>
            <a
              href="{{ url_for('.cluster_eval_topic', rts_id=rts_id) }}"
              class="btn {{ "btn-secondary" if relevant_count == clustered_count else "btn-danger"}}"
              >
              {{ clustered_count }}
            </a>
          </td>
          <td>
            {% if topic_id %}
            <a
              href="{{ url_for('main.topic', topic_id=topic_id) }}"
              class="btn btn-secondary"
              >
              Queries
            </a>
            {% endif %}
          </td>
        </tr>
      {%- endfor %}
    </tbody>
  </table>
{% endblock content %}

flock-web/flock_web/blueprints/collection/templates/collection/features.html
{% extends "base.html" %}

{% block content %}

  {{ render_pagination(page) }}

  <table class="table table-striped">
    <thead>
      <tr>
        <th style="max-width: 300px" class="text-capitalize">{{ feature_name }}</th>
        {% if other_feature_name and not other_feature_values %}
          <th class="text-capitalize">{{ other_feature_name }}</th>
        {% elif other_feature_values %}
          {% for other_feature_value in other_feature_values %}
            <th class="text-capitalize">{{ other_feature_value }}</th>
          {% endfor %}
        {%- endif %}
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      {%- for item in items %}
        <tr>
          <td style="max-width: 300px">
            <a href="{{ url_for('.tweets', **{feature_name: item.feature}) }}">{{ item.feature }}</a>
          </td>
          {% if other_feature_name and not other_feature_values %}
            <td><a href="{{ restricted_url('.tweets', **{other_feature_name: item.other_feature}) }}">{{ item.other_feature }}</a></td>
          {% elif other_feature_values %}
            {% for other_feature_value in other_feature_values %}
              <td class="text-capitalize">
                <a href="{{ restricted_url('.tweets', **{feature_name: item.feature, other_feature_name: other_feature_value}) }}">
                {{ item[other_feature_value]|humanize('intcomma') if item[other_feature_value] else '' }}
              </td>
            {% endfor %}
          {%- endif %}
          <td>
            <a href="{{ restricted_url('.tweets', **{feature_name: item.feature}) }}">{{ item[-1]|humanize('intcomma') }}</a>
          </td>
        {%- endfor %}
        </tr>
    </tbody>
  </table>

  {{ render_pagination(page) }}

{% endblock %}

flock-web/flock_web/blueprints/collection/templates/collection/index.html
{% extends "collection/base.html" %}
{% import "collection/macro.html" as m %}

{% block title %} {{ config.get('collection:{}'.format(g.collection), {}).get('title', g.collection) }} {% endblock %}

{% block content %}

  <div class="jumbotron">
    <form action="{{ url_for('.tweets') }}" method="get">
      <div class="row justify-content-md-center" id="sidebar-search-box">
        <div class="col-5">
          <input type="text" class="form-control form-control-lg" placeholder="Search" name="q" {% if query %} value="{{ query }}" {% endif %}>
        </div>
        <div class="col-3 col-lg-2">
          <button class="btn btn-success btn-lg my-2 my-sm-0" type="submit" style="width: 100%;">Search</button>
        </div>
      </div>
    </form>
  </div>

  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

{% endblock content%}

flock-web/flock_web/blueprints/collection/templates/collection/macro.html
{% macro render_tweets(tweets, topic=None, show_images=False, relevance_judgments=None, show_alert=True, eval_relevance_judgments=None) %}

  {% if show_alert and not tweets %}
    <div class="alert alert-danger" role="alert">
      <h4 class="mb=0">Nothing has been found!</h4>
    </div>
  {% endif %}

  {% if tweets %}
    <div class="card-columns tweet-selection">
      {%- for tweet in tweets %}
        <div class='card tweet-outer'>
          <blockquote class="twitter-tweet card-blockquote" data-dnt="true" {% if not show_images %}data-cards="hidden"{% endif %}>
            <div class="card custom-tweet">
              <div class="card-block">
                <header>
                  <p class="twitter-user-name">{{ tweet.features.user_info.screen_name }}</p>
                  <small class="text-muted">@{{ tweet.features.user_info.screen_name }}</small>
                </header>
                <blockquote class="card-blockquote">
                  <p dir="ltr" class="card-text">
                    {{ tweet.text }}
                  </p>
                  <small>
                    <a href="https://twitter.com/{{ tweet.features.user_info.screen_name }}/status/{{ tweet.tweet_id }}">{{ tweet.created_at }}</a>
                  </small>
                </blockquote>
              </div>
            </div>
          </blockquote>
          {% if topic %}
            {% set j = relevance_judgments.get(tweet.tweet_id, 0) %}
            <div class="tweet-outer-meta btn-group btn-block ml-1" data-toggle="buttons">
              <label class="btn btn-outline-success mb-0 {% if j == 1 %}active{% endif %}" style="width: 33%"  onclick="send_relevance(this, '{{ tweet.tweet_id }}', {{ topic.id}}, 1)">
                <input type="radio" name="relevance" id="1" autocomplete="off" {% if j == 1 %}checked{% endif %}>Relevant
              </label>
              <label class="btn btn-outline-secondary mb-0 {% if j == 0 %}active{% endif %}" style="width: 33%" onclick="send_relevance(this, '{{ tweet.tweet_id}}', {{ topic.id }}, 0)">
                <input type="radio" name="relevance" id="0" autocomplete="off" {% if j == 0 %}checked{% endif %}>Unjudged
              </label>
              <label class="btn btn-outline-danger mb-0  {% if j == -1 %}active{% endif %}" style="width: 33%" onclick="send_relevance(this, '{{ tweet.tweet_id}}', {{ topic.id }}, -1)">
                <input type="radio" name="relevance" id="-1" autocomplete="off"  {% if j == -1 %}checked{% endif %}>Irrelevant
              </label>
            </div>
          {% endif %}
          {% if eval_relevance_judgments %}
            {% set j = eval_relevance_judgments.get(tweet.tweet_id, -1) %}
            <div class="tweet-outer-meta ml-0">
              {% if j  and j > 0 %}
                <a href="#" class="btn btn-success disabled w-100" role="button" aria-disabled="true">Relevant</a>
              {% elif j == 0 %}
                <a href="#" class="btn btn-danger disabled w-100" role="button" aria-disabled="true">Irrelevant</a>
              {% else %}
                <a href="#" class="btn btn-secondary disabled w-100" role="button" aria-disabled="true">Not judged</a>
              {% endif %}
            </div>
          {% endif %}
        </div>
      {%- endfor %}
    </div>
  {% endif %}
{% endmacro %}


{% macro render_stats(feature_name, feature_alias, features, active_feature_names, collection, hidden_fields) %}
  <div class="card sidebar-element">
    <div class="card-header container">
      <div class="row justify-content-between">
      <form class="form-inline w-100" action="{{url_for('.tweets', collection=collection)}}" method="get">
        <div class="col">
          <h3>{{ feature_alias }}</h3>
        </div>
        <div class="col col-md-auto">
          <input class="form-control mr-1" type="text" id="{{feature_name}}_input" name="{{feature_name}}">
          <button type="submit" class="btn btn-secondary"><i class="fa fa-plus-square" aria-hidden="true"></i></button>
        </div>

        {% for k, v in hidden_fields %}
          <input type="hidden" name="{{ k }}" value="{{ v }}">
        {% endfor %}

      </form>
      </div>
    </div>
    <div class="card-columns feature-stats-container">
      {% for feature, count in features %}
        <div class="card">
          <div class="list-group list-group-flush">
            <a class="list-group-item list-group-item-action flex-column align-items-start feature-stats-item feature-item {{ 'active' if feature in active_feature_names}}" href="{{ restricted_url('.tweets', include={feature_name: feature} if feature not in active_feature_names else {}, exclude={} if feature not in active_feature_names else {feature_name: feature}, cluster=None)  }}">
              {{ feature }} ({{ count|humanize('intcomma') }})
            </a>
          </div>
        </div>
        {% endfor %}

  {#       {\# <a class="btn btn-outline-danger btn-sm" href="{{ restricted_url('.tweets', include={feature_name: '-{}'.format(feature)}, exclude={feature_name: feature}) }}" role="button"> #\}  #}
  {#       {\#   <i class="fa fa-times" aria-hidden="true"></i> #\}  #}
  {#       {\# </a> #\}  #}
  {#   {\# </div> #\} #}
  </div>
{# {% endfor %}  #}

{% endmacro %}


{% macro render_tweet_count(tweet_count) %}
  <p>
    There are {{ tweet_count|humanize('intcomma') }} tweets.
  </p>
 {% endmacro%}

flock-web/flock_web/blueprints/collection/templates/collection/tweets.html
{% extends "collection/base.html" %}
{% import "collection/macro.html" as m %}

{% block title %} {{ g.query }} | {{ config.get('collection:{}'.format(g.collection), {}).get('title', g.collection) }} {% endblock %}


{% block content %}

  <div class="row">

    <div class="col-xl-4 col-md-6 bg-faded sidebar bd-links">

      {% if g.topic %}
        <div class="alert alert-info" role="alert">
          <strong>Topic: </strong> <a href="{{url_for('main.topic', topic_id=g.topic.id)}}" class="alert-link">"{{ g.topic.title }}"</a>.
        </div>
      {% endif %}

      <div id="tweet_count"></div>

      <form class="sidebar-element" action="{{ url_for('.tweets') }}" method="get">
        <div class="row" id="sidebar-search-box">
          <div class="col-10">
            <input type="text" class="form-control" placeholder="Search" name="q" {% if g.query %} value="{{ g.query }}" {% endif %}>
          </div>
          <div class="col-2">
            <button class="btn btn-outline-success my-2 my-sm-0 w-100" type="submit">Search</button>
          </div>
        </div>
        {% for k, v in query_form_hidden_fields %}
          <input type="hidden" name="{{ k }}" value="{{ v }}">
        {% endfor %}
      </form>

      {% if g.topic.queries %}
      <div class="card">
        <h3 class="card-header">Queries</h3>
        <div class="list-group">
            {% for q in g.topic.queries|unique(attribute='query') %}
             <a
               class="list-group-item {{ 'active' if q.query == g.query else '' }}"
               href="{{ url_for('collection.tweets', collection=g.collection, q=q.query, filter=q.filter, cluster=q.cluster, topic=g.topic.id, **q.filter_args_dict) }}"
             >{{ q.query }}</a>
            </li>
            {% endfor %}
        </div>
      </div>

      {% endif %}

      <div id="screen_names_stats"></div>
      <div id="hashtags_stats"></div>
      <div id="user_mentions_stats"></div>

      <div id="clusters">
        <p>
          <div id='clustering_progress_container' class="progress" style="display: none;">
            <div id='clustering_progress' class="progress-bar" role="progressbar"></div>
          </div>
          <button id="start-clustering-task" class="btn btn-outline-success w-100">Cluster</button>
        </p>
      </div>

    </div>

    <main class="col-xl-8 offset-xl-4">
      <div id="tweets">
        <h1>Loading...</h1>
      </div>
    </main>

  </div>

{% endblock content %}

{% block navbar_extra %}

  <form class="form-inline" action="{{ url_for('main.topic_post') }}" method="post" >

    <label class="mr-sm-2 navbar-text" for="inlineTopicSelect">Topic</label>
    <select name="topic_id" class="custom-select mb-2 mr-sm-2 mb-sm-0" id="inlineTopicSelect" onchange="this.form.submit()">
      <option value="__none__" {% if not topic %}selected{% endif %}></option>
      <option value="-1" style="font-weight: bold;">New ({{ g.query }})</option>
      {% for topic in topics %}
        <option value="{{ topic.id }}" {% if topic.id == g.topic.id %}selected{% endif %}>{{ topic.title }}</option>
      {% endfor %}
    </select>

    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <input type="hidden" name="selection_args" value="{{  selection_for_topic_args }}">
    <input type="hidden" name="return_to_collection" value="{{ g.collection }}">

  </form>

  {% block navbar_extra_collection %}
  {% endblock navbar_extra_collection %}

  {% endblock navbar_extra %}

  {% block extra_scripts %}
  <script>
   function start_clustering_task() {
       $.post({
           url: '{{ url_for('.cluster') }}',
           data: {
               selection_args: JSON.stringify({{ selection_args|safe }}),
               from_url: '{{ restricted_url('.tweets')|safe }}',
               csrf_token: '{{ csrf_token() }}',
           },
           success: function(data, status, request) {
               var status_url = request.getResponseHeader('Location');
               status_url = status_url + '?' + window.location.search.slice(1);

               update_progress(status_url);
           },
           error: function() {
               console.log('Unexpected error');
           }
       });
   }

   function update_progress(status_url){
       $.getJSON(status_url, function(data){
           $('#clustering_progress_container').show();
           $('#start-clustering-task').hide();

           if (data['state'] == 'PROGRESS') {
               var progress = data['info']['current'] / data['info']['total'] * 100;
               $('#clustering_progress').attr('style', 'width:' + progress + '%;');
               $('#clustering_progress').html(data['info']['status']);
           }
           else if (data['state'] == 'SUCCESS') {
               $('#clustering_progress_container').hide();
               $('#clusters').html(data['html'])

               return;
           } else if (data['state'] == 'FAILURE') {
               alert('Clustering error.')
               return;
           }
           setTimeout(function(){update_progress(status_url);}, 2000);
       });
   }

   function reset_tabindex(times=10){
       $('*').attr('tabindex', -1);
       $('.btn-group[data-toggle=buttons] .btn').attr('tabindex', 0)

       if (times > 0) {
           setTimeout(function(){reset_tabindex(times - 1)}, 500);
       }
   }

   function get_task(destination, url, request_data, load_tweets, delay=300){
       $.get({
           url: url,
           data: request_data,
           success: function(data, status, request){
               if (data['state'] == 'SUCCESS'){
                   $(destination).html(data['html']);
                   if (load_tweets && (typeof twttr !== 'undefined')) {
                       twttr.widgets.load();
                   }
               } else {
                   setTimeout(function(){get_task(destination, url, request_data, load_tweets, delay*1.2)}, delay);
               }
           }
       });
   }

   $(document).ready(function() {
       $('#start-clustering-task').click(start_clustering_task);

       {% for f_name, task in stats %}
       get_task(
           '#{{ f_name }}_stats',
           '{{ restricted_url('.task_result', task_id=task.id)|safe }}',
           {},
           false
       );
       {% endfor %}
       get_task(
           '#tweet_count',
           '{{ url_for('.task_result', task_id=tweet_count.id) }}',
           {},
           false
       )

       $('.btn-group[data-toggle=buttons] .btn').keydown(function(e) {
           if (e.which == 13 || e.which == 32) {
               $(this).click()
           }
       });
   });

   paceOptions = {
       elements: {
           selectors: ['#tweet_count p', '#screen_names_stats div', '#hashtags_stats div', '#user_mentions_stats div', 'iframe.twitter-tweet-rendered,#tweets .alert']
       }
   };
  </script>

  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  <script src="{{ url_for('static', filename='bundle.js') }}"></script>
  <script>
    window.TWEET_TASK_URL = '{{ url_for('.task_result', task_id=tweet_task.id, topic=g.topic.id if g.topic else None) }}';

    window.JUDGE_TWEET_URL = '{{ url_for('main.relevance') }}';
    window.CSRF_TOKEN = '{{ csrf_token() }}';
    window.SELECTION_ARGS = {{ selection_for_topic_args|safe }};
    window.COLLECTION = '{{ g.collection }}';

    window.devTweets();
  </script>
  {% endblock extra_scripts %}